module.exports={
    conatinerFull:{
        width:'100%',
        height:'100%',
        backgroundColor:'black',
        alignItems:'center',
        justifyContent:'center'
    },
    logo1:{
        height:70,
        resizeMode:'contain',
        marginBottom:20

    },
    hr80:{
        width:'80%',
        height:1,
        backgroundColor:'gray',
        marginVertical:20
    },
    row:{
        flexDirection:'row',
        alignItems:'center',
        marginVertical:10
    },
    goback:{
        flexDirection:'row',
        position:'absolute',
        top:50,
        left:20,
        alignItems:'center'
    },
    icons1:{
        color:'white',
        fontSize:30,
    }
}